name: reddit_clone
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_native_splash: ^2.2.9
  flutter_screenutil: ^5.5.4
  http: ^0.13.5
  intl: ^0.17.0
  logger: ^1.1.0
  lottie: ^1.4.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/reddit_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/reddit.json
    - assets/reddit_logo.png
